project:
  type: website
  output-dir: _site

website:
  title: "My Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
