---
title: "Data Preparation"
author: "Your Name"
date: today
format: html
editor: visual
execute:
  warning: false
  echo: false
---

```{r}
source(here::here("_common.R"))
```

```{r}
dt_long_price_change = read_csv(here("data/processed/actual_event_long_window.csv"))
long_window_plot_data = read_csv(here("data/processed/plot_data_long_window.csv"))
```

Replicating Figure 1

```{r}
library(ggplot2)
library(stringr)
library(dplyr)

legend_levels = c(
    "1 Year Treasury",
    "5 Year Treasury",
    "10 Year Treasury",
    "20 Year Treasury",
    "30 Year Treasury"
)

# Colors for the levels
custom_colors <- c(
  "1 Year Treasury" = "#00B798",  # Teal
  "5 Year Treasury" = "#FF8C30",  # Orange
  "10 Year Treasury" = "#777BEA", # Blue/Violet
  "20 Year Treasury" = "#EA7ADA", # Pink/Magenta
  "30 Year Treasury" = "#79D03A"  # Green
)


```

```{r}

long_window_plot_data |> 
    inner_join(bond_metadata) |> 
    mutate(label = paste(maturity,"Year", data_group)) |> select(-description) |> 
    mutate(
        median_price_change_bps = median_price_change * 100
    ) |> 
    filter(str_detect(symbol, "^DGS")) |> 
    # Explicitly set factor order for labels
    mutate(label = factor(label, levels = legend_levels)) |>
        ggplot(aes(
        x = window_index,
        y = median_price_change_bps,
        color = label
    )) +
    geom_line(size=1.5, alpha=0.8) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
    scale_color_manual(values = custom_colors, name = "Series") +
    labs(
        title = "Median change across events",
        x = "Relative time in days (0 = event day)",
        y = "Basis points (bp)"
    ) +
    theme_minimal()

```

```{r}

long_window_plot_data |> 
    inner_join(bond_metadata) |> 
    mutate(label = paste(maturity,"Year", data_group)) |> select(-description) |> 
    mutate(
        median_price_change_bps = median_abs_price_change * 100
    ) |> 
    filter(str_detect(symbol, "^DGS")) |> 
    # Explicitly set factor order for labels
    mutate(label = factor(label, levels = legend_levels)) |>
        ggplot(aes(
        x = window_index,
        y = median_price_change_bps,
        color = label
    )) +
    geom_line(size=1.5, alpha=0.8) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "black") +
    scale_color_manual(values = custom_colors, name = "Series") +
    labs(
        title = "Median absolute change across events",
        x = "Relative time in days (0 = event day)",
        y = "Basis points (bp)"
    ) +
    theme_minimal()
```
